name: Jobs Share job data
defaults:
  run:
    shell: bash
on: push
jobs:
  before:
    runs-on: ubuntu-latest
    steps:
      - id: generate # ステップのID
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}" # ステップレベルの出力値
    outputs:
      result: ${{ steps.generate.outputs.result }} # ジョブレベルの出力値
  after:
    needs: [before]
    runs-on: ubuntu-latest
    steps:
      - env:
          RESULT: ${{ needs.before.outputs.result }} # 依存jobのステップレベルの出力値を取得
        run: echo "${RESULT}"
# ジョブデータの出力における典型的な構造
# 1.ステップにidキーを指定
# 2.ステップ内で${GITHUB_OUTPUT}環境変数に値を出力する
# 3.出力値をジョブのoutputsキーへ出力する（stepsコンテキスト経由で出力する）
