name: GITHUB_ENV
on: push
defaults:
  run:
    shell: bash
jobs:
  github-env-set:
    runs-on: ubuntu-latest
    steps:
      - run: echo "RESULT=hello in github env" >> "${GITHUB_ENV}"
      - run: echo "${RESULT}"
