name: Hash functions
on: push
defaults:
  run:
    shell: bash
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml') }}
          # ハッシュファイルの生成
