name: Status Check functions
on: push
defaults:
  run:
    shell: bash
jobs:
  fail-check:
    runs-on: ubuntu-latest
    steps:
      # - run: exit 1
      # ステータスが0以外のためエラーが発生する
      - run: exit 0
      # actionsのエラー回避のため、0に変更
      - run: echo "Hello after exit 1"
        if: ${{failure()}}
        # ifでfailure()メソッドを呼んでいるため、エラーが発生した場合に実行される
